AWSTemplateFormatVersion: "2010-09-09"
Description: "OrchardLite Prerequisites - Enhanced Service-Linked Role Validation"

Resources:
  # Lambda Execution Role
  ServiceLinkedRoleLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EnhancedServiceLinkedRoleManagement
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                  - iam:GetRole
                  - iam:ListAttachedRolePolicies
                  - iam:ListRolePolicies
                Resource: "*"

  # Enhanced Lambda Function
  ServiceLinkedRoleFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-EnhancedRoleManager"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt ServiceLinkedRoleLambdaRole.Arn
      Timeout: 90
      Code:
        ZipFile: |
          import boto3
          import json
          import cfnresponse

          def validate_role(iam, role_name, service):
              try:
                  role = iam.get_role(RoleName=role_name)['Role']
                  issues = []
                  
                  # Check trust policy
                  trust_policy = role['AssumeRolePolicyDocument']
                  trust_valid = False
                  for stmt in trust_policy.get('Statement', []):
                      principal = stmt.get('Principal', {})
                      if isinstance(principal, dict) and 'Service' in principal:
                          services = principal['Service']
                          if isinstance(services, str):
                              services = [services]
                          if service in services:
                              trust_valid = True
                              break
                  
                  if not trust_valid:
                      issues.append(f"Invalid trust policy for {service}")
                  
                  # Check role path
                  if not role['Path'].startswith('/aws-service-role/'):
                      issues.append("Invalid service-linked role path")
                  
                  # Check attached policies
                  try:
                      policies = iam.list_attached_role_policies(RoleName=role_name)
                      if not policies['AttachedPolicies']:
                          issues.append("No managed policies attached")
                  except Exception:
                      issues.append("Cannot check attached policies")
                  
                  return "VALIDATED" if not issues else f"ISSUES: {'; '.join(issues)}"
                  
              except Exception as e:
                  return f"VALIDATION_ERROR: {str(e)}"

          def lambda_handler(event, context):
              try:
                  iam = boto3.client('iam')
                  
                  if event['RequestType'] in ['Create', 'Update']:
                      roles = [
                          ('ecs.amazonaws.com', 'AWSServiceRoleForECS'),
                          ('elasticloadbalancing.amazonaws.com', 'AWSServiceRoleForElasticLoadBalancing'),
                          ('rds.amazonaws.com', 'AWSServiceRoleForRDS')
                      ]
                      
                      results = {}
                      
                      for service, role_name in roles:
                          try:
                              # First check if role exists
                              iam.get_role(RoleName=role_name)
                              
                              # Role exists, now validate it
                              validation = validate_role(iam, role_name, service)
                              
                              if validation == "VALIDATED":
                                  results[service] = "VALIDATED: Role exists with correct configuration"
                              else:
                                  results[service] = validation
                                  
                          except iam.exceptions.NoSuchEntityException:
                              # Role doesn't exist, create it
                              try:
                                  print(f"Creating missing service-linked role for {service}")
                                  response = iam.create_service_linked_role(AWSServiceName=service)
                                  results[service] = f"CREATED: Role created successfully - {response['Role']['Arn']}"
                              except Exception as e:
                                  if 'has been taken' in str(e) or 'already exists' in str(e):
                                      # Race condition - role was created between check and create
                                      print(f"Race condition detected for {service}, re-validating...")
                                      try:
                                          validation = validate_role(iam, role_name, service)
                                          results[service] = f"RACE_RESOLVED: Role created by another process - {validation}"
                                      except Exception:
                                          results[service] = "RACE_RESOLVED: Role created by another process"
                                  else:
                                      results[service] = f"CREATE_ERROR: Failed to create role - {str(e)}"
                          except Exception as e:
                              results[service] = f"CHECK_ERROR: Unexpected error - {str(e)}"
                      
                      # Summary
                      created = sum(1 for v in results.values() if v.startswith('CREATED'))
                      validated = sum(1 for v in results.values() if v.startswith('VALIDATED'))
                      issues = sum(1 for v in results.values() if 'ISSUES:' in v)
                      errors = sum(1 for v in results.values() if 'ERROR' in v)
                      
                      results['Summary'] = f"Created: {created}, Validated: {validated}, Issues: {issues}, Errors: {errors}"
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, results)
                  else:
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {"Status": "Delete - No action"})
                      
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Error": str(e)})

  # Custom Resource
  ServiceLinkedRoleManager:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt ServiceLinkedRoleFunction.Arn

Outputs:
  # Individual Role Status
  ECSServiceLinkedRoleStatus:
    Description: "ECS Service-Linked Role (AWSServiceRoleForECS) Status"
    Value: !GetAtt ServiceLinkedRoleManager.ecs.amazonaws.com
    Export:
      Name: OrchardLite-ECS-ServiceRole-Status

  ELBServiceLinkedRoleStatus:
    Description: "ELB Service-Linked Role (AWSServiceRoleForElasticLoadBalancing) Status"
    Value: !GetAtt ServiceLinkedRoleManager.elasticloadbalancing.amazonaws.com
    Export:
      Name: OrchardLite-ELB-ServiceRole-Status

  RDSServiceLinkedRoleStatus:
    Description: "RDS Service-Linked Role (AWSServiceRoleForRDS) Status"
    Value: !GetAtt ServiceLinkedRoleManager.rds.amazonaws.com
    Export:
      Name: OrchardLite-RDS-ServiceRole-Status

  # Summary Information
  ValidationSummary:
    Description: "Service-Linked Role Management Summary (Created/Validated/Issues/Errors)"
    Value: !GetAtt ServiceLinkedRoleManager.Summary

  # Required Roles List
  RequiredServiceLinkedRoles:
    Description: "List of service-linked roles required for OrchardLite CMS"
    Value: "AWSServiceRoleForECS, AWSServiceRoleForElasticLoadBalancing, AWSServiceRoleForRDS"

  RequiredServices:
    Description: "AWS services that need service-linked roles"
    Value: "Amazon ECS, Elastic Load Balancing, Amazon RDS"

  # Deployment Readiness
  OrchardLiteReadiness:
    Description: "Ready to deploy OrchardLite CMS application"
    Value: !Sub
      - "Prerequisites Status: ${summary} - Check individual role status above"
      - summary: !GetAtt ServiceLinkedRoleManager.Summary

  NextSteps:
    Description: "Next steps after service-linked role setup"
    Value: "Deploy orchardlite-cms.yaml template - all required service-linked roles are configured"

  # Troubleshooting Information
  TroubleshootingGuide:
    Description: "If OrchardLite deployment fails with 'Unable to assume service linked role'"
    Value: "Check individual role status outputs above. Re-run this template if any roles show ISSUES or ERRORS"

  # Role Details for Reference
  ECSRoleDetails:
    Description: "ECS Service-Linked Role Details"
    Value: "Role: AWSServiceRoleForECS | Service: ecs.amazonaws.com | Purpose: ECS cluster operations"

  ELBRoleDetails:
    Description: "ELB Service-Linked Role Details"
    Value: "Role: AWSServiceRoleForElasticLoadBalancing | Service: elasticloadbalancing.amazonaws.com | Purpose: Load balancer operations"

  RDSRoleDetails:
    Description: "RDS Service-Linked Role Details"
    Value: "Role: AWSServiceRoleForRDS | Service: rds.amazonaws.com | Purpose: RDS database operations"
