AWSTemplateFormatVersion: "2010-09-09"
Description: "Security Module - Database Password Migration to AWS Secrets Manager for Enhanced Security"

Parameters:
  # Existing Resource Identifiers
  AuroraClusterIdentifier:
    Type: String
    Description: Existing Aurora Serverless Cluster Identifier
    Default: "orchardlite-aurora-serverless"

  DMSSourceEndpointIdentifier:
    Type: String
    Description: Existing DMS Source Endpoint Identifier
    Default: "orchardlite-source-rds-endpoint"

  DMSTargetEndpointIdentifier:
    Type: String
    Description: Existing DMS Target Endpoint Identifier
    Default: "orchardlite-target-aurora-endpoint"

  # Current Password Values (for migration)
  CurrentAuroraPassword:
    Type: String
    Description: Current Aurora master password (will be stored in Secrets Manager)
    NoEcho: true
    Default: "AuroraPassword2024!"

  CurrentRDSPassword:
    Type: String
    Description: Current RDS source password (will be stored in Secrets Manager)
    NoEcho: true
    Default: "OrchardPassword2024!"

  # Database Configuration
  AuroraUsername:
    Type: String
    Description: Aurora master username
    Default: "auroraadmin"

  RDSUsername:
    Type: String
    Description: RDS source username
    Default: "orchardadmin"

  RDSEndpoint:
    Type: String
    Description: RDS source endpoint
    Default: "orchardlite-mysql-enterprise.xxxxxxxxx.us-west-1.rds.amazonaws.com"

  AuroraEndpoint:
    Type: String
    Description: Aurora cluster endpoint
    Default: "orchardlite-aurora-serverless.cluster-xxxxxxxxx.us-west-1.rds.amazonaws.com"

Resources:
  # ============================================================================
  # KMS KEY FOR SECRETS ENCRYPTION
  # ============================================================================

  SecretsManagerKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS Key for OrchardLite Secrets Manager encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow Secrets Manager Service
            Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:ReEncrypt*
            Resource: "*"
          - Sid: Allow RDS Service
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: "*"
          - Sid: Allow DMS Service
            Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: "*"
      Tags:
        - Key: Name
          Value: OrchardLite-SecretsManager-KMS-Key
        - Key: Module
          Value: Security
        - Key: Purpose
          Value: SecretsEncryption

  SecretsManagerKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/orchardlite-secrets-manager
      TargetKeyId: !Ref SecretsManagerKMSKey

  # ============================================================================
  # SECRETS MANAGER SECRETS
  # ============================================================================

  AuroraServerlessSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: orchardlite/aurora/master-password
      Description: "Aurora Serverless master password for OrchardLite workshop"
      KmsKeyId: !Ref SecretsManagerKMSKey
      SecretString: !Sub |
        {
          "username": "${AuroraUsername}",
          "password": "${CurrentAuroraPassword}",
          "engine": "mysql",
          "host": "${AuroraEndpoint}",
          "port": 3306,
          "dbClusterIdentifier": "${AuroraClusterIdentifier}"
        }
      Tags:
        - Key: Name
          Value: OrchardLite-Aurora-Secret
        - Key: Module
          Value: Security
        - Key: Purpose
          Value: DatabaseCredentials

  RDSSourceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: orchardlite/rds/source-password
      Description: "RDS source database password for OrchardLite migration"
      KmsKeyId: !Ref SecretsManagerKMSKey
      SecretString: !Sub |
        {
          "username": "${RDSUsername}",
          "password": "${CurrentRDSPassword}",
          "engine": "mysql",
          "host": "${RDSEndpoint}",
          "port": 3306,
          "dbname": "OrchardLiteDB"
        }
      Tags:
        - Key: Name
          Value: OrchardLite-RDS-Source-Secret
        - Key: Module
          Value: Security
        - Key: Purpose
          Value: DatabaseCredentials

  # ============================================================================
  # IAM ROLES AND POLICIES
  # ============================================================================

  SecretsManagerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "OrchardLite-SecretsManager-Access-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
                - dms.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: Name
          Value: OrchardLite-SecretsManager-Access-Role
        - Key: Module
          Value: Security

  DatabaseSecretsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: OrchardLite-Database-Secrets-Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowSecretsManagerAccess
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref AuroraServerlessSecret
              - !Ref RDSSourceSecret
          - Sid: AllowKMSDecryption
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: !GetAtt SecretsManagerKMSKey.Arn
      Roles:
        - !Ref SecretsManagerAccessRole

  # ============================================================================
  # SECRETS MANAGER RESOURCE POLICIES
  # ============================================================================

  AuroraSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref AuroraServerlessSecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRDSAccess
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: "*"
            Condition:
              StringEquals:
                "secretsmanager:ResourceTag/Purpose": "DatabaseCredentials"

  RDSSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref RDSSourceSecret
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowDMSAccess
            Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: "*"
            Condition:
              StringEquals:
                "secretsmanager:ResourceTag/Purpose": "DatabaseCredentials"

Outputs:
  # Essential Secret ARNs
  AuroraSecretArn:
    Description: Aurora Serverless Secret ARN
    Value: !Ref AuroraServerlessSecret
    Export:
      Name: OrchardLite-Security-Aurora-Secret-ARN

  RDSSourceSecretArn:
    Description: RDS Source Secret ARN
    Value: !Ref RDSSourceSecret
    Export:
      Name: OrchardLite-Security-RDS-Source-Secret-ARN

  # Migration Status
  MigrationStatus:
    Description: Next steps for completing the migration
    Value: "Secrets created successfully. Update Aurora cluster and DMS endpoints to reference these secrets using AWS CLI or Console."
